package:
  name: nano-min
  version: 0.0.1

source:
  path: ../

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - scikit-build-core
    - python
    - cmake
    - nanobind

  host:
    - python

  run:
    - python


test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

outputs:
  - name: nano-min
    script: copy_files.bat

about:
  home: https://github.com/Krande/nano-cpp-minimal
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "An example demonstrating a minimal python wrapper for c++ code"

extra:
  recipe-maintainers:
    - Krande