package:
  name: nano-min
  version: 0.1.0

source:
  path: ../

build:
  number: 0
  script: python -m pip install -v .

requirements:
  build:
    - python
    - scikit-build-core
    - nanobind
    - numpy
    - pip
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/nanobind-minimal
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "An example demonstrating a minimal python wrapper for c++ code"

extra:
  recipe-maintainers:
    - Krande
